### ISSUE TITLE
Search for criteria to evaluate success or not.

### ISSUE THREAD

**Issue by shp216** [LlamaTouch/Evaluator#4]
Sorry to ask again. I am trying to evaluate an agent against the generated dataset provided within llamatouch. Is there a place where the criteria for measuring success for each episode are specified? I can't find any criteria in the code in both Evaluator and AgentEnv you uploaded. Thank you!

**Comment by lizhang20** [comment]
Hi, the evaluation method of LlamaTouch is implemented in file: https://github.com/LlamaTouch/Evaluator/blob/main/evaluator/testbed_evaluator.py. The name might be a bit confusing, and we plan to rename it later. In short, it reads all essential states in the dataset of each task and checks whether the task execution traces (generated by your agent) go through all these states. Only if all essential states are passed is the task considered completed.

**Comment by shp216** [comment]
I understand that I need to organize the results from my agent in a way similar to autodroid.py or appagent.py in llamatouch for evaluation. However, I'm a bit confused about how exactly the folder structure for the agent's results should be. I seem to encounter errors when I try to organize it like the dataset structure you provided on the drive. From looking at the load_testbed_trace_by_path function in task_trace.py, I understood that it should be organized as follows:

My_agent
│
└───Episode_num
    │
    ├───screenshot
    │   └───[Screenshot files, ex) 0.png, 1.png, ...]
    │
    ├───view_hierarchy
    │   └───[view hierarchy files, ex): 0.json, 1.json, ...]
    │
    ├───activity
    │   └───[activity files, ex) 0.activity, 1.activity, ...]
    │
    └───action
        └───[action files, ex): 0.action, 1.action, ...]
        
        
  Is it right???

**Comment by lizhang20** [comment]
Thank you for your attention to this project.
Currently the implementation for loading agent execution traces is determined by how they are stored. The agent execution traces are loaded individually by passing an episode_id as the parameter.

For example, if you implement your own `XXXAgent` class by inheriting the [`MobileAgent`](https://github.com/LlamaTouch/Evaluator/blob/main/evaluator/agent.py) base class, you only need to implement two methods: `load_exec_trace_by_episode` and `load_predicted_action_by_episode`.

Our exec traces are organized as follows (as an example):

```
AutoDroid_traces
├── 0                   <- episode_id
│  ├── action
│  │  ├── 0.action
│  │  ├── 1.action
│  │  ├── 2.action
│  ├── activity
│  │  ├── 0.activity
│  │  ├── 1.activity
│  │  ├── 2.activity
│  ├── screenshot
│  │  ├── 0.png
│  │  ├── 1.png
│  │  ├── 2.png
│  ├── view_hierarchy
│  │  ├── 0.json
│  │  ├── 1.json
│  │  ├── 2.json
│  └── xml
│     ├── 0.xml
│     ├── 1.xml
│     ├── 2.xml
├── 00150550311485070814                <- episode_id
│  ├── action
│  │  ├── 0.action
│  │  ├── 1.action
│  │  ├── 2.action
│  ├── activity
│  │  ├── 0.activity
│  │  ├── 1.activity
│  │  ├── 2.activity
.....
```

The current version of Evaluator might encounter some bugs. We are working on fixing it and will soon release the traces used in our evaluation for a concrete example to run the end-to-end evaluation workflow.

**Comment by shp216** [comment]
Thank you so much!!

**Comment by lizhang20** [comment]
Hi shp216, we have uploaded the agent execution traces collected during the evaluation of AutoUI on AgentEnv. You can check out the latest README, download the traces, and run different evaluation methods in this repository. We hope this provides an example for running the end-to-end evaluation workflow on new agents/traces!

**Comment by shp216** [comment]
Hi lizhang! Thank you very much for your help with my research. I am progressing well with llamatouch, but there are a few issues that I need help with, so I have one more question to ask.
 
 First, I assumed that the gr_trace was the exec_trace conducted by the agent and proceeded by restructuring the folder as follows. I also modified the load_testbed_trace_by_path function to fit the structure and ensure that the evaluation proceeds accordingly.
 
MyAgent_dataset
|
------------------------- generated
                                |
                               ------------------- 0 <--- episode_num
                                                       |
                                                       ------- 0.activity
                                                       ------- 0.json
                                                       ------- 0.png
                                                       ------- 0.vh
                                                       ------- 0.xml
                                                       ... and so on
                               ------------------- 1 <--- episode_num
                               ------------------- 2 <--- episode_num
                               ... (393 generated tasks)

Assuming that the gr_trace is the result of the agent's actions, I checked and confirmed that a success rate of 100% is achievable with this structure. I then attempted to evaluate by running the actual agent and matching the folder structure accordingly.

However, I did not achieve a 100% success rate and kept encountering errors. It seems the issue arises in the check_essential_state_match function of testbed_evaluator, but I am not exactly sure what the problem is.

Main Error example) 
ERROR:TestbedEvaluator:Failed to evaluate episode 41027976563613149918: object of type 'float' has no len() - This is caused from check_click_match function
ERROR:TestbedEvaluator:Failed to evaluate episode 52302499763200999728: 'temp_id'

I apologize for asking so many questions and bothering you. Thank you for your excellent research!

**Comment by lizhang20** [comment]
Thank you for your detailed and quick feedback! We will reproduce this issue and verify the results. We will respond to you as soon as we find the problems.

**Comment by shp216** [comment]
Thank you for your quick response!! I really appreciate about it.

**Comment by lizhang20** [comment]
> Hi lizhang! Thank you very much for your help with my research. I am progressing well with llamatouch, but there are a few issues that I need help with, so I have one more question to ask.
> 
> First, I assumed that the gr_trace was the exec_trace conducted by the agent and proceeded by restructuring the folder as follows. I also modified the load_testbed_trace_by_path function to fit the structure and ensure that the evaluation proceeds accordingly.
> 
> MyAgent_dataset | ------------------------- generated | ------------------- 0 <--- episode_num | ------- 0.activity ------- 0.json ------- 0.png ------- 0.vh ------- 0.xml ... and so on ------------------- 1 <--- episode_num ------------------- 2 <--- episode_num ... (393 generated tasks)
> 
> Assuming that the gr_trace is the result of the agent's actions, I checked and confirmed that a success rate of 100% is achievable with this structure. I then attempted to evaluate by running the actual agent and matching the folder structure accordingly.
> 
> However, I did not achieve a 100% success rate and kept encountering errors. It seems the issue arises in the check_essential_state_match function of testbed_evaluator, but I am not exactly sure what the problem is.
> 
> Main Error example) ERROR:TestbedEvaluator:Failed to evaluate episode 41027976563613149918: object of type 'float' has no len() - This is caused from check_click_match function ERROR:TestbedEvaluator:Failed to evaluate episode 52302499763200999728: 'temp_id'
> 
> I apologize for asking so many questions and bothering you. Thank you for your excellent research!

I think the main issue is the different file structures and contents between agent execution traces and the ground-truth dataset, as they are generated by different tools that do not follow the same output file format. I highly recommend using our provided traces to test the entire workflow. You can refer to the documentation at https://github.com/LlamaTouch/Evaluator/blob/main/example/evaluate_collected_traces.md.

Please feel free to contact us if you cannot run the code or have additional questions. Thank you!
